### ISSUE TITLE
Scottish Govt data includes external org IDs but chart shows type of recipient "Unknown"

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/covid19-tracker#23]
https://covidtracker.threesixtygiving.org/funder/GB-GOR-DA1020

![image](https://user-images.githubusercontent.com/20462640/110109768-cac64780-7da5-11eb-9c97-e85ff5f471c7.png)

**Comment by KDuerden** [comment]
Also get the same issue with William Grant Foundation: https://covidtracker.threesixtygiving.org/funder/360G-WilliamGrantFdn
They are Scottish funder, but is that just a coincidence?

**Comment by drkane** [comment]
Hmm - that's weird. The correct categories are showing in the download so they're in there somewhere. Might be our old friend caching again. I'll take a look.

**Comment by drkane** [comment]
Looks like the OSCR data hasn't been loaded into the datastore, and that's causing the issue. I'll raise a ticket.

**Comment by KDuerden** [comment]
Ok thanks. The OSCR data is being added ok in the Funders in Common spreadsheets that I ran it this morning. Is that being fetched via a different route?

**Comment by drkane** [comment]
Yes, I think that's getting it direct from FTC, but we could probably amend it to use the datastore instead.

Ticket raised on the scottish charities issue: https://opendataservices.plan.io/issues/28665

**Comment by drkane** [comment]
This is now fixed ([see this issue on the datastore](https://github.com/ThreeSixtyGiving/datastore/pull/75)) - organisations are showing as registered charities.

There's now a separate issue that the types being shown aren't formatted very nicely - they're showing as "registered-charities" rather than "Registered charities". I'll open a separate issue for that.
